[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "yalmp_scripts"
version = "0.1.0"
dependencies = [
    "pytaglib",
]

[project.optional-dependencies]
dev = ["ruff", "mypy"]